#!/usr/bin/env bash
REPO=$(pwd)

cd $HOME/code/git

install_packages
set_zsh
mkdirs
symlink
install_tamzen
clone_scripts
# set_pape

install_paru() {
    git clone https://aur.archlinux.org/paru-bin.git
    cd paru-bin
    makepkg -si
}

set_zsh() {
    sudo chsh -s $(which zsh) $USER
}

install_packages() {
    # install important packages
    sudo pacman -S --noconfirm --needed - < $REPO/etc/pac.deps
    install_paru
    # install aur packages
    paru -S --noconfirm - < $REPO/etc/aur.deps
}

mkdirs() {
    mkdir -p $HOME/.config/polybar
    mkdir $HOME/.config/bspwm
    mkdir $HOME/.config/sxhkd
    mkdir $HOME/.config/alacritty
    mkdir $HOME/.config/lf
    mkdir $HOME/.config/paru
    mkdir $HOME/.gnupg
    mkdir $HOME/moria
}

symlink() {
    # zsh
    ln -s $REPO/zsh/* $HOME/
    
    # polybar
    ln -s $REPO/polybar/* $HOME/.config/polybar/
    
    # bspwm
    ln -s $REPO/sxhkd/sxhkdrc $HOME/.config/sxhkd/sxhkdrc
    ln -s $REPO/bspwm/* $HOME/.config/bspwm/
   
    # term
    ln -s $REPO/alacritty/* $HOME/.config/alacritty/
    ln -s $REPO/vim/.vimrc $HOME/.vimrc
    ln -s $REPO/lf/lfrc $HOME/.config/lf/lfrc
    ln -s $REPO/tmux/.tmux.conf $HOME/.tmux.conf

    # gpg
    ln -s $REPO/gpg/gpg-agent.conf $HOME/.gnupg/gpg-agent.conf
    ln -s $REPO/gpg/gpg.conf $HOME/.gnupg/gpg.conf

    # misc
    ln -s $REPO/paru/paru.conf $HOME/.config/paru/paru.conf
    ln -s $REPO/etc/user-dirs.dirs $HOME/.config/
    sudo ln -s $REPO/etc/40-libinput.conf /etc/X11/xorg.conf.d/
    sudo ln -s $REPO/etc/local.conf /etc/fonts/
    sudo cat $REPO/etc/fstab >> /etc/fstab
}

clone_scripts() {
    # clone scripts
    cd $HOME/code/git
    git clone https://github.com/skovati/scripts
}

install_tamzen() {
    # set fonts
    mkdir $HOME/.fonts
    git clone https://github.com/sunaku/tamzen-font .fonts/tamzen-font
    xset +fp ~/.fonts/tamzen-font/bdf
    xset fp rehash
}

set_pape() {
    # set pape
    mkdir -p $HOME/docs/pics
    cd $HOME/docs/pics
    wget https://papes.skovati.com/nature/water.png
    feh --bg-scale $HOME/docs/pics
}

other() {
    xdg-settings set default-web-browser firefox.desktop
    xdg-mime default org.pwmt.zathura.desktop application/epub
    xdg-mime default org.pwmt.zathura.desktop application/pdf
    xdg-mime default mpv.desktop video/mp4
    xdg-mime default mpv.desktop video/mkv
    xdg-mime default sxiv.dekstop image/jpeg
    xdg-mime default sxiv.dekstop image/jpg
    xdg-mime default sxiv.dekstop image/png
}
