#!/usr/bin/env bash

query=$(echo -n "" | dmenu -p "DuckDuckGo Search: ")
if [ -n "$query" ]; then
    base_url="https://duckduckgo.com/?q="
    query=$base_url$(echo $query | sed "s/ /+/g")
    firefox $query
fi    

