#!/bin/sh

# global vars
WIKIDIR=$HOME/dev/git/wiki

encrypt_wiki() {
    tar zcf $WIKIDIR/wiki.tar.gz -C $WIKIDIR wiki || {
        echo "unable to package wiki..."
        exit 1
    }
    gpg -q -o $WIKIDIR/wiki.tar.gz.gpg -sear D82CB814F5C6956ABD2DBD405026E406B7B3818F $WIKIDIR/wiki.tar.gz || {
        echo "unable to encrypt wiki... try manually"
        exit 1
    }
    shred -u $WIKIDIR/wiki.tar.gz
    rm -rf $WIKIDIR/wiki
}

decrypt_wiki() {
    gpg -q -o $WIKIDIR/wiki.tar.gz --decrypt $WIKIDIR/wiki.tar.gz.gpg || {
        echo "unable to decrypt and/or verify the signature... try manually"
        exit 1
    }
    tar zxf $WIKIDIR/wiki.tar.gz -C $WIKIDIR && \
    shred -u $WIKIDIR/wiki.tar.gz*
}

case "$1" in
    edit | "")
        [ -d $WIKIDIR/wiki ] || {
            echo "wiki was encrypted, decrypting with gpg..."
            decrypt_wiki
        }
        $EDITOR $WIKIDIR/wiki/index.md
    ;;
    push)
        encrypt_wiki
        cd $WIKIDIR
        git commit -S -am "update wiki" && git push origin main
        cd -
    ;;
    encrypt)
        encrypt_wiki
    ;;
    decrypt)
        decrypt_wiki
    ;;
    *)
        echo "usage: crypt [option]\n\t-e encrypt wiki\n\t-d decrypt wiki"
    ;;
esac
