#!/usr/bin/env bash

# us servers in chicago
us_servers=("us18" "us22" "us23" "us129" "us130" "us131" "us132" "us133")

usage() {
    echo "
    Usage: wire [command] [location]
    commands: up, down, status
    locations: lab, us
    "
}

# command line args
case $1 in
    status)
        echo "Currently connected to:"
        doas wg | grep interface | awk '{print $2}'
        ;;
    up)
        case $2 in 
            lab)
                echo "Connecting to lab at $(dig +short skovati.duckdns.org)..."
                doas wg-quick up lab
                ;;
            us)
                # choose randomly for different ips
                rand=$[$RANDOM % ${#us_servers[@]}]
                server="mullvad-${us_servers[rand]}"
                echo "Connecting to $server over WireGuard..."
                doas wg-quick up $server > /dev/null 2>&1
                echo "Success, new ip: $(curl -s ifconfig.io)"
                ;;
            *)
                usage
                ;;
        esac
        ;;
    down)
        case $2 in 
            lab)
                echo "Disconnecting from lab..."
                doas wg-quick down lab
                ;;
            us)
                # grep to find current mullvad wg connection
                curr_server=$(doas wg | grep mullvad | awk '{print $2}')
                echo "Disconnecting from $curr_server..."
                doas wg-quick down $curr_server > /dev/null 2>&1
                echo "Success, new ip: $(curl -s ifconfig.io)"
                ;;
            *)
                usage
                ;;
        esac
        ;;
    *)
        usage
        ;;
esac
