#! /bin/sh

sxhkd &
feh --bg-scale /home/skovati/docs/pics/flowers.jpg
wal -R
picom --vsync --backend glx -GCb --config /dev/null
pgrep redshift || redshift -t 5500:4200 -l 43:-89 -m randr &
xsetroot -cursor_name left_ptr &
xset r rate 300 30
pgrep bspswallow || bspswallow &
xss-lock -l -- xsecurelock
bash /home/skovati/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         2
bspc config window_gap          20

bspc config top_padding 65
bspc config bottom_padding 35
bspc config left_padding 35
bspc config right_padding 35
bspc config top_monocle_padding -65
bspc config bottom_monocle_padding -35
bspc config left_monocle_padding -35
bspc config right_monocle_padding -35


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

. "/home/skovati/.cache/wal/colors.sh"

bspc config normal_border_color "#444444"
bspc config active_border_color "$background"
bspc config focused_border_color "$foreground"

bspc config focus_follows_pointer true
bspc config click_to_focus button1 

bspc monitor DP-1 -d 1 2 3 4 5 6 7
