#! /bin/sh

#######################################
# autostart
#######################################

sxhkd &
feh --bg-scale /home/skovati/documents/pictures/books.jpg
wal -R
xset s off -dpms
picom --vsync --backend glx -GCb --config /dev/null
pgrep redshift || redshift -t 5500:3800 -l 43:-89 -m randr &
xsetroot -cursor_name left_ptr &
xss-lock -l -- xsecurelock
bash /home/skovati/.config/polybar/launch.sh &

#######################################
# bsp window spacing
#######################################

bspc config top_padding 55
bspc config bottom_padding 25
bspc config left_padding 25
bspc config right_padding 25

bspc config top_monocle_padding -55
bspc config bottom_monocle_padding -25
bspc config left_monocle_padding -25
bspc config right_monocle_padding -25

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width         3
bspc config window_gap          15

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

#######################################
# colors
#######################################

. "/home/skovati/.cache/wal/colors.sh"
bspc config normal_border_color "#444444"
bspc config focused_border_color "$foreground"
bspc config presel_feedback_color "#444444"

#######################################
# misc
#######################################

bspc config focus_follows_pointer false
bspc config click_to_focus button1 

bspc monitor eDP1 -d 1 2 3 4 5 6 7
bspc monitor DP-1 -d 8

#######################################
# per-app config
#######################################

bspc rule -a Zathura state=tiled
