#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         2
bspc config window_gap          15

bspc config top_padding 55
bspc config bottom_padding 25
bspc config left_padding 25
bspc config right_padding 25
bspc config top_monocle_padding -55
bspc config bottom_monocle_padding -25
bspc config left_monocle_padding -25
bspc config right_monocle_padding -25


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

. "/home/skovati/.cache/wal/colors.sh"

bspc config normal_border_color "#444444"
bspc config focused_border_color "$foreground"

bspc config focus_follows_pointer false
bspc config click_to_focus button1 

bspc monitor eDP-1 -d 1 2 3 4 5 6 7

sh /home/skovati/.config/bspwm/auto

