#!/bin/bash

usage() {
echo "
Usage...
=======================================
which VPN would you like to connect to?
-d Disconnect
-w WireGuard(aws)
-n Nordvpn
-o OpenVPN(Nord)
-s OpenVPN(seedbox)
-c WiscVPN
"
}

connect() {
echo "Please wait while we connect you..."
}

if [ $# -eq 0 ] 
then 
  usage
  exit 1
fi

echo "
Welcome to Luke's VPN Service.
Current IP: $(curl -s ifconfig.io)
========================================"
while getopts dwnsco option 
do 
  case "${option}" in
    d)
      echo "You will be disconnected. Please wait..."
      sudo killall openvpn > /dev/null 2>&1
      nordvpn d > /dev/null 2>&1
      sudo killall openconnect > /dev/null 2>&1
      sudo wg-quick down wg0 > /dev/null 2>&1
      sudo wg-quick up wg1 > /dev/null 2>&1
    ;;
    w)
      echo "You have chosen WireGuard(aws)"
      connect
      sudo wg-quick down wg1 > /dev/null 2>&1 
      sudo wg-quick up wg0 > /dev/null 2>&1
    ;;
    n) 
      echo "You have chosen Nordvpn."
      connect
      nordvpn c
    ;;
    o) 
      echo "You have chosen OpenVPN(Nord)."
      connect
      cd /home/skovati/code/openvpn
      sudo openvpn --config us3415.nordvpn.com.udp1194.ovpn --daemon
    ;;
    s)  
      echo "You have chosen OpenVPN(seedbox)."
      connect
      cd /home/skovati/code/openvpn
      sudo openvpn --config  skovati-1.ovpn --daemon
    ;;
    c) 
      echo "You have chosen WiscVPN."
      connect
      sudo openconnect --protocol=gp -b --user=ljjurgella compsci.vpn.wisc.edu
    ;;
    h) 
      usage 
      exit 1
    ;; 
  esac
done

sleep 2
echo "========================================
Your new IP: $(curl -s ifconfig.io)
Come again!
"

