#!/bin/sh

########################################
# WM CONFIG
########################################

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0xe8e4d9
riverctl border-color-unfocused 0x6e6e6e
riverctl border-width 3

# Set keyboard repeat rate
riverctl set-repeat 50 300

TRACKPAD="2:7:SynPS/2_Synaptics_TouchPad"
riverctl input "$TRACKPAD" events enabled
riverctl input "$TRACKPAD" accel-profile flat
riverctl input "$TRACKPAD" pointer-accel 0.1
riverctl input "$TRACKPAD" click-method clickfinger
riverctl input "$TRACKPAD" drag enabled
riverctl input "$TRACKPAD" drag-lock disabled
riverctl input "$TRACKPAD" disable-while-typing enabled
riverctl input "$TRACKPAD" middle-emulation enabled
riverctl input "$TRACKPAD" natural-scroll enabled
riverctl input "$TRACKPAD" left-handed disabled
riverctl input "$TRACKPAD" tap enabled
riverctl input "$TRACKPAD" tap-button-map left-right-middle
riverctl input "$TRACKPAD" scroll-method two-finger
riverctl input "$TRACKPAD" scroll-factor 0.01

riverctl attach-mode bottom

########################################
# KEYBINDS
########################################

# Use the "logo" key as the primary modifier
mod="Mod4"

riverctl map normal $mod Return spawn alacritty

riverctl map normal $mod W spawn librewolf

riverctl map normal $mod D spawn run

# Mod+Q to close the focused view
riverctl map normal $mod Q close

riverctl map normal $mod+Shift+Control L spawn lock

# Mod+Shift+E to exit river
riverctl map normal $mod+Shift Q exit

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod Space zoom

# Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
riverctl map -repeat normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map -repeat normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# Mod+Alt+{H,J,K,L} to move views
riverctl map -repeat normal $mod+Mod1 H move left 100
riverctl map -repeat normal $mod+Mod1 J move down 100
riverctl map -repeat normal $mod+Mod1 K move up 100
riverctl map -repeat normal $mod+Mod1 L move right 100

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+Mod1+Control H snap left
riverctl map normal $mod+Mod1+Control J snap down
riverctl map normal $mod+Mod1+Control K snap up
riverctl map normal $mod+Mod1+Control L snap right

# Mod+Alt+Shif+{H,J,K,L} to resize views
riverctl map -repeat normal $mod+Mod1+Shift H resize horizontal -50
riverctl map -repeat normal $mod+Mod1+Shift J resize vertical 50
riverctl map -repeat normal $mod+Mod1+Shift K resize vertical -50
riverctl map -repeat normal $mod+Mod1+Shift L resize horizontal 50

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9); do
    tags=$((1 << (i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod "$i" set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift "$i" set-view-tags $tags

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+Control "$i" toggle-focused-tags $tags

    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control "$i" toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Mod+Space to toggle float
riverctl map normal $mod+Shift Space toggle-float

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ -5%'
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ +5%'
    riverctl map $mode None XF86AudioMute         spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'

    # Control screen backlight brighness
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl -c backlight s +1%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl -c backlight s 1%-'
done

########################################
# AUTO
########################################
wl-paste -t text --watch clipman store --no-persist &
swaybg -i /home/skovati/docs/pics/pape -m fill &
yambar &

riverctl default-layout rivertile
rivertile -view-padding 4 -outer-padding 8
