XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"
XDG_DATA_HOME="$HOME/.local/share"

XDG_DESKTOP_DIR="$HOME/"
XDG_DOCUMENTS_DIR="$HOME/docs/"
XDG_DOWNLOAD_DIR="$HOME/downs/"
XDG_PICTURES_DIR="$HOME/docs/pics/"
