#!/bin/zsh

########################################
# EXPORTS
########################################
# actually important
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.nix-profile/bin"
export EDITOR="nvim"
export VISUAL="alacritty -e 'nvim'"
export READER="zathura"
export IMAGE="nsxiv"
export TERMINAL="alacritty"
export TZ='America/Chicago'
export MANPAGER='nvim +Man!'
export MOZ_ENABLE_WAYLAND=1
export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
export GOPATH="$HOME/dev/go"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$HOME/.cargo/bin:$PATH"
export _JAVA_AWT_WM_NONREPARENTING=1

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_RUNTIME_DIR="/run/user/$UID"
export XDG_CURRENT_DESKTOP="sway"

# purely rice
export BAT_THEME="ansi"
export GPG_TTY=$(tty)

# source secrets
[ -f $HOME/.env ] && source $HOME/.env

########################################
# ALIASES
########################################
alias cp="cp -v"
alias mv="mv -iv"
alias rm="rm -vI"
alias ip="ip --color=auto"
alias vim="nvim"
alias sudo="doas"
alias one="ping -c 5 1.1.1.1"
alias vrc="nvim ~/dev/git/dotfiles/nvim/init.lua ~/dev/git/dotfiles/nvim/lua/plugins.lua"
alias sx="nsxiv -b -a"
alias rcp="rsync -avzhP --stats"
alias z="zathura --fork"
alias xc="xclip -sel clipboard -i"
alias xp="xclip -sel clipboard -o"
alias k="kubectl"
alias in="task add +in"
alias todo="task -in"

if !which exa > /dev/null 2>&1; then
    alias ls="ls --color -F"
    export LS_COLORS='rs=0:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=30;41:sg=30;43:tw=30;42:ow=30;42:st=30;44:ex=01;32:'
fi

########################################
# CONFIG
########################################
HISTFILE="$XDG_DATA_HOME/zsh/history"
mkdir -p "$(dirname "$HISTFILE")"
HISTSIZE=1000000
SAVEHIST=$HISTSIZE
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt interactivecomments
unsetopt beep
bindkey -v # vim mode

autoload -Uz promptinit edit-command-line vcs_info
promptinit

# git branch in prompt
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '(%b)'

zle -N edit-command-line
bindkey '\ev' edit-command-line # open command in vim with alt-v

zstyle ":completion:*" menu select
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char

bindkey "^?" backward-delete-char

function zle-keymap-select {
    if [[ ${KEYMAP} == vicmd ]]; then
        echo -ne '\e[2 q'
    elif [[ ${KEYMAP} == main ]] ||
        [[ ${KEYMAP} == viins ]] ||
        [[ ${KEYMAP} = '' ]]; then
        echo -ne '\e[4 q'
    fi
}
zle -N zle-keymap-select

# ci", ci', ci`, di", etc
autoload -U select-quoted
zle -N select-quoted
for m in visual viopp; do
    for c in {a,i}{\',\",\`}; do
        bindkey -M $m $c select-quoted
    done
done

setopt auto_pushd

setopt prompt_subst
PROMPT=' %F{green}%~%f%F{yellow}$vcs_info_msg_0_ '

export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#707070'
typeset -A ZSH_HIGHLIGHT_STYLES
export ZSH_HIGHLIGHT_STYLES[comment]='fg=#707070'
